version: '3'
services:
    frontend:
        build:
            context: ./frontend
            dockerfile: Dockerfile
        environment:
            - NODE_ENV=development
        volumes:
            - ./frontend/:/usr/src/frontend
        command: sh -c 'yarn start'
        ports:
            - 8000:3000
        tty: true