version: '3'
services:
    frontend:
        build:
            context: ./frontend
            dockerfile: Dockerfile
        environment:
            - NODE_ENV=development
        volumes:
            - ./frontend/:/usr/src/frontend
        command: sh -c 'yarn start'
        ports:
            - 8001:3000
        tty: true

    backend:
        build:
            context: ./backend
            dockerfile: Dockerfile
        volumes:
            - ./backend:/user/src/backend
        ports:
            - 8000:8000
        tty: true